version: '3.1'

services:
  db:
    image: mariadb:10.6
    volumes:
      - db:/var/www/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
  site:
    depends_on:
      - db
    volumes:
      - html_folder:/var/www/html
      - ./tr-plugin:/var/www/html/wp-content/plugins/tr-plugin
      - ./tr-theme:/var/www/html/wp-content/themes/tr-theme
    image: php-local:local
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8086:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
volumes:
  db:
  html_folder: